on:
  pull_request:
    branches: [main]
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        run: echo  '${{ toJSON(github) }} -- ${{ toJson(job) }} '

      - name: Make Release
        if: startsWith( github.ref, 'refs/tags/releases/')
        run: echo "****Running 'Make Release'""
