on:
  pull_request:
    branches: [main]
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Dump Context
        run: echo  '${{ toJSON(github) }} -- ${{ toJson(job) }} '

      - name: Make Release
        if: startsWith( github.ref, 'refs/tags/v')
        run: echo "****Running 'Make Release'"

      - name: Create Release
        if: startsWith( github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
